### ISSUE TITLE
RequestWatcher doesn't purge the content of views

### ISSUE THREAD

**Issue by LWlook** [laravel/telescope#1548] opened 2024-11-19 15:35 UTC
### Telescope Version

5.2.5

### Laravel Version

11.32.0

### PHP Version

8.3.13

### Database Driver & Version

MariaDB

### Description

In the RequestWatcher class, on line 201, the response data is converted directly to an array without first applying the contentWithinLimits method. This results in the full response data being logged in Telescope, even when a smaller size_limit configuration is set.

### Steps To Reproduce

1. Create a view that renders a large table or a similar substantial data structure.
2. Check the recorded response data in Telescope.
3. Notice that the full response content is logged despite the configured size_limit.

**Comment by crynobone** [comment] 2024-11-19 23:28
Duplicate of #1547. I would welcome a reproduction code as indicated in the issue.

**Closed as completed by crynobone** 2024-11-19 23:28 UTC

**Comment by aske-cph** [comment] 2025-01-10 12:48
This issue is still present. Telescope ignores size limit set like :

        Watchers\RequestWatcher::class => [
			'size_limit' => env('TELESCOPE_RESPONSE_SIZE_LIMIT', 10),
		],
		
It simply dumps whatever to the content field, quickly creating several gigabytes of data if you have a large SPA application with lots of data preloaded, so it's pretty severe and makes telescope unusable for our size.
