### ISSUE TITLE
Jobs are in pending status!

### ISSUE THREAD

**Issue by Rux77** [laravel/telescope#507] opened 2018-12-16 06:56 UTC
I am using Redis and Horizon to mange my queues..

When I use `php artisan queue:work redis` to process the jobs , the jobs's status in both Horizon and Telescope is successfully changed to `success` status.

On the other hand, when using `php artisan horizon` the jobs are in a `success` status in Horizon, yet Telescope shows these jobs as in a `pending` status!

**Comment by themsaid** [comment] 2018-12-16 12:52
duplicate of https://github.com/laravel/telescope/issues/503

**Closed by themsaid** 2018-12-16 12:52 UTC

**Comment by Rux77** [comment] 2018-12-17 08:04
How to reproduce this issue?

1 - run `php artisan horizon` before dispatching any job..
2 - dispatch a job from Observer or Events listeners..

It seems that Telescope doesn't catch jobs's events probably in this scenario...

**Comment by fridzema** [comment] 2018-12-18 09:50
Same issue here. 
Horizon says it is finished successfully, but telescope stays pending forever.

**Comment by Rux77** [comment] 2018-12-20 13:19
@themsaid

is this on your radar?

**Comment by themsaid** [comment] 2018-12-20 13:58
I can't replicate it no matter what I test, horizon and telescope are running nicely together.

**Comment by Rux77** [comment] 2018-12-21 11:12
I did a fresh laravel install with the same configuration as my old project ( which has the issue ) and everything is working nicely between horizon and telescope like you said.

I will dig more and see whats happening with my old project.

**Comment by jny986** [comment] 2021-06-17 02:20
Just incase anyone finds this and is looking for an answer.
I had the same issue with Telescope and AWS/SQS queues and found that the problem was fixed by restarting the queue workers.
