### ISSUE TITLE
ExtractProperties in JobWatcher causes Memory Leaks

### ISSUE THREAD

**Issue by Patabugen** [laravel/telescope#853] opened 2020-03-27 17:15 UTC
- Telescope Version: 2.1
- Laravel Version: 6.5.0
- PHP Version: 7.3.8
- Database Driver & Version: redis 6.0-rc2

### Description:
I've got a MySQL table with 430,000 rows (of Waypoints - ID, lat, lng). I've got a job which goes through them all in chunks (`using Db::chunkById()`) and queues another job to process them.

I've spent today debugging out of memory errors, and found the root of it - which is this line:

https://github.com/laravel/telescope/blob/b6f903533d054030f0c24def89fa7c57fd33c3ed/src/Watchers/JobWatcher.php#L147

And specifically if I comment out ` json_decode(json_encode($value), true),` here:

https://github.com/laravel/telescope/blob/b6f903533d054030f0c24def89fa7c57fd33c3ed/src/ExtractProperties.php#L30

Then the problem goes away.

I've got a bit stuck following it back up after that.

### Steps To Reproduce:
I've had a quick go at making a single file to reproduce the bug but without success.

If this sounds like an actual bug that might get fixed I'll try again - but wanted to reach out with what I've found so far for some input from the developers.

Does this look like something we want to try and fix?

**Comment by driesvints** [comment] 2020-03-28 11:08
I'll leave this open for others to help out.

**Comment by driesvints** [comment] 2020-04-09 15:29
Since the problem can't be reproduced I'm closing this.

**Closed by driesvints** 2020-04-09 15:29 UTC
Labels: needs more info

**Comment by jwadhams** [comment] 2022-11-23 22:56
I'd have a hell of a time creating a reproduction case, but I also have an issue where I've got a loop adding Jobs to a Batch, and Telescope runs out of memory.

My solution, inspired by https://github.com/laravel/telescope/issues/173, was to just 
`Telescope::stop()` at the top of the job, then `Telescope::start()` at the bottom of the job. 

Hope that helps future Googlers.
