### ISSUE TITLE
Exception entries do not get stored when a job fails

### ISSUE THREAD

**Issue by benignant** [laravel/telescope#626] opened 2019-05-08 16:43 UTC
- Telescope Version: 2.0.4
- Laravel Version: 5.8.16
- PHP Version: 7.3.3
- Database Driver & Version: MySQL 5.7.19

### Description:
Exception entries do not get stored when a job fails. The exception does however get stored as part of the job entry. Is this the expected behavior? It seems inconsistent since when a job triggers an exception but does not fail, the exception entry does get logged. I would propose that exception entries should get stored regardless of whether or not the job fails. The exception would then be linked to the job via the `batch_id`, so you wouldn't even need to store the exception in the job entry. Linking the exception to the job would also have the added benefit of indicating that a pending or processed job has already been attempted and resulted in an exception. Currently there is no way to tell that a job had to be attempted multiple times.

### Steps To Reproduce:

1. Process a job that triggers an exception but does not fail (because it will be retried)
2. Now process the job again, but this time ensure that it fails
3. Note that the first time the job was processed an exception entry was stored but not the second time

**Comment by themsaid** [comment] 2019-05-31 08:22
Can't replicate, works for me. Also doesn't seem like other people are reporting the same issue so I believe you'll need to look into your project code.

**Comment by taylorotwell** [comment] 2019-12-06 20:27
Can't recreate this either. Closing for now.

**Closed by taylorotwell** 2019-12-06 20:27 UTC

**Comment by antoinelame** [comment] 2022-01-27 18:12
I'm posting this message a few years later, for those like me who face the same issue.

The behavior described by @benignant is still actual and I see it on all the Laravel projects I work on.

Exceptions triggered by jobs **do not appear** in the Exceptions page of Telescope (`/telescope/exceptions`). However, they are showed on the detail page of a job that failed (`/telescope/jobs/{uuid}`). I don't know if this is the expected behavior or not.

This is because in `Laravel\Telescope\Watchers\ExceptionWatcher@recordException`, the `Telescope::isRecording()` value is equals to `false`.

```php
/**
 * Record an exception was logged.
 *
 * @param  \Illuminate\Log\Events\MessageLogged  $event
 * @return void
 */
public function recordException(MessageLogged $event)
{
    if (! Telescope::isRecording() || $this->shouldIgnore($event)) {
        return;
    }

    // ...
}
```

That said, this could be the expected behavior.

**Comment by mshamaseen** [comment] 2024-09-30 21:33
Returning to this after 2 years, isn't this a weird behavior? Shouldn't Telescope log job exceptions by default?
