### ISSUE TITLE
New Installation of Telescope fails

### ISSUE THREAD

**Issue by kvn1234** [laravel/telescope#732] opened 2019-09-11 13:25 UTC
- Telescope Version: 2.1
- Laravel Version: 6.0.3
- PHP Version: 7.3.6
- Database Driver & Version:

### Description:
I upgraded my 5.8 project yesterday to 6 yesterday using Laravel Shift. Everything seems to be fine with that. Installing Telescope (previously uninstalled), however, fails at `Publishing Telescope Configuration...`

### Steps To Reproduce:
1. `composer require laravel/telescope`
2. `php artisan telescope:install`
3. Errors with: 
```
Publishing Telescope Service Provider...
Publishing Telescope Assets...
Publishing Telescope Configuration...

   ErrorException  : file_get_contents(/home/vagrant/xxx/app/Providers/TelescopeServiceProvider.php): failed to open stream: No such file or directory

  at /home/vagrant/xxx/vendor/laravel/telescope/src/Console/InstallCommand.php:80
    76|
    77|         file_put_contents(app_path('Providers/TelescopeServiceProvider.php'), str_replace(
    78|             "namespace App\Providers;",
    79|             "namespace {$namespace}\Providers;",
  > 80|             file_get_contents(app_path('Providers/TelescopeServiceProvider.php'))
    81|         ));
    82|     }
    83| }
    84|

  Exception trace:

  1   file_get_contents("/home/vagrant/xxx/app/Providers/TelescopeServiceProvider.php")
      /home/vagrant/xxx/vendor/laravel/telescope/src/Console/InstallCommand.php:80

  2   Laravel\Telescope\Console\InstallCommand::registerTelescopeServiceProvider()
      /home/vagrant/xxx/vendor/laravel/telescope/src/Console/InstallCommand.php:43
```

4. `App\Providers\TelescopeServiceProvider::class,` gets written into app.php but neither the actual service provider nor the migrations are actually created as files. 
5. Using `php artisan telescope:publish` returns 
```
Publishing complete.
Publishing complete.
```

 (yes, twice like that) but nothing actually changes or gets published.

This is my first time trying to use Telescope and I might be missing something obvious but I'm simply following the instructions and it's not working, so I'd appreciate any help here.

**Comment by Calinou** [comment] 2019-09-11 19:13
I can reproduce the same issue on Telescope 2.1 using Laravel 6.0.3 and PHP 7.3.9.

**Comment by Abdulmanan0315** [comment] 2019-09-14 19:11
i am also facing the same on laravel 6.0  and telescope 2.1

<img width="929" alt="Capture" src="https://user-images.githubusercontent.com/20532497/64912770-431df080-d74d-11e9-8b96-a2a5349302bc.PNG">

**Comment by barryvdh** [comment] 2019-09-14 21:11
Do you have a folder 'Providers'?

**Comment by Abdulmanan0315** [comment] 2019-09-14 22:06
Yes All the provoders are in laravel app/Providers by default

**Comment by Abdulmanan0315** [comment] 2019-09-14 22:08
Is there going to be a fix for this as telescope is an awesome tool for laravel

**Comment by kvn1234** [comment] 2019-09-14 22:50
I have a Providers folder as well.

**Comment by dennispeld** [comment] 2019-09-22 11:29
Exactly the same problem. Cannot proceed any further, fails on telescope:install step. Impossible to use the tool.  Trying on Laravel Framework 6.0.3, Telescope 2.1

**Comment by lokoo** [comment] 2019-09-25 13:20
I'm using the exact same as kvn1234. When running the `php artisan telescope:install` it gives me 

> Telescope scaffolding installed successfully

but it says `nothing to migrate` after going to the next step (running `php artisan migrate`). Even after removing it etc, I can't seem to get it to wrok.

**Comment by Gragot** [comment] 2019-09-27 00:48
Same problem:

laravel/framework: 6.0.4
laravel/telescope: 2.1
PHP: 7.3.10

For some reason I don't know, it seems that the command "php artisan telescope:install" does not work and does not copy the file "TelescopeServiceProvider.php" into "app\Providers" (The directory exist)

**Comment by lk77** [comment] 2019-10-06 11:17
Hello,

same problem here, i have to copy manually the provider from stubs.

**Comment by dieguiviti** [comment] 2019-10-08 07:26
> I'm using the exact same as kvn1234. When running the `php artisan telescope:install` it gives me
> 
> > Telescope scaffolding installed successfully
> 
> but it says `nothing to migrate` after going to the next step (running `php artisan migrate`). Even after removing it etc, I can't seem to get it to wrok.

Same, there isn't a fix anywhere that i can see yet

**Comment by drbyte** [comment] 2019-10-10 16:56
The unfortunate workaround is: remove `TELESCOPE_ENABLED=false` from your `.env`, because Telescope's commands are skipped when it's set to false.

The problem is super simple to reproduce:
```sh
laravel new telescope_test
cd telescope_test
echo TELESCOPE_ENABLED=false >> .env
composer require laravel/telescope
php artisan telescope:install
``` 
Instantly you'll get all the errors.
```text
Publishing Telescope Service Provider...
Publishing Telescope Assets...
Publishing Telescope Configuration...

   ErrorException  : file_get_contents(/Users/me/Sites/telescope_test/app/Providers/TelescopeServiceProvider.php): failed to open stream: No such file or directory

  at /Users/me/Sites/telescope_test/vendor/laravel/telescope/src/Console/InstallCommand.php:80
    76|
    77|         file_put_contents(app_path('Providers/TelescopeServiceProvider.php'), str_replace(
    78|             "namespace App\Providers;",
    79|             "namespace {$namespace}\Providers;",
  > 80|             file_get_contents(app_path('Providers/TelescopeServiceProvider.php'))
    81|         ));
    82|     }
    83| }
    84|

  Exception trace:

  1   file_get_contents("/Users/me/Sites/telescope_test/app/Providers/TelescopeServiceProvider.php")
      /Users/me/Sites/telescope_test/vendor/laravel/telescope/src/Console/InstallCommand.php:80

  2   Laravel\Telescope\Console\InstallCommand::registerTelescopeServiceProvider()
      /Users/me/Sites/telescope_test/vendor/laravel/telescope/src/Console/InstallCommand.php:43

  Please use the argument -v to see more details.
```

You can also see that `php artisan vendor:publish` doesn't display any Telescope stuff when `TELESCOPE_ENABLED=false`.

**Comment by kvn1234** [comment] 2019-10-10 17:21
I don't have TELESCOPE_ENABLED as an environment variable. Never did. I never got far enough into the installation procedures to need to configure it.

**Comment by drbyte** [comment] 2019-10-10 17:25
Okay, perhaps it's a separate issue. I'll report it separately.

**Comment by kvn1234** [comment] 2019-10-10 17:26
I just tried again and it fails with the same errors I listed above.  I appreciate the effort to try to help,  though.  I guess I'm just destined to not be able to use it.

**Comment by lk77** [comment] 2019-10-11 07:22
I don't have TELESCOPE_ENBLED either,
fresh laravel install and fresh telescope install.

**Comment by pascallieverse** [comment] 2019-10-11 07:36
Same problem here..

- Telescope Version: 2.1
- Laravel Version: 6.0.3
- PHP Version: 7.2.11

After running `php artisan telescope:install`  only the service provider is added to the providers array inside config/app.php and nothing gets published meanwhile the provider folder exists.

@taylorotwell Could you have a look into this issue, it seems that a lot of people with laravel 6 have issues while publishing.

Also it seems like TELESCOPE_ENABLED has nothing to do with this issue.

**Comment by kvn1234** [comment] 2019-10-11 14:27
Mine got weirder--after trying again yesterday, I discovered that I now I have the telescope migrations in my database, though it still doesn't publish anything else.  I could probably copy up the stubs from the package and be on my way, but I don't see my way to trusting something that's not working correctly from install.

**Comment by lk77** [comment] 2019-10-11 14:45
@kvn1234 i agree, it's okay in dev, but it's certainly not 6.x ready in production.

**Comment by pszucs** [comment] 2019-10-14 12:12
I got it working by manually copying the `TelescopeServiceProvider` file to the `Providers` directory:

`cp vendor/laravel/telescope/stubs/TelescopeServiceProvider.stub app/Providers/TelescopeServiceProvider.php`

I also added the `TELESCOPE_ENABLED=true` line to the `.env` file, just in case.

**Comment by lk77** [comment] 2019-10-14 12:16
I also have an issue that can be related to the installation issue,
i have 419 errors, and i was forced to add telescope to the $except array in VerifyCsrfToken middleware.

**Comment by TWithers** [comment] 2019-10-17 03:58
Frustrating. I have used this before at the beginning of the year and it was like a 5 minute process to get this thing up and running. Now I am copying files and chasing down errors, and it still isn't running 30 minutes later.

**Comment by adajusr** [comment] 2019-10-23 22:35
Hi! I'm having the same issue.  I have installed:

Laravel Version: 6.0.3
PHP Version: 7.2.11

and trying to install Telescope Version: 2.1, it says Telescope scaffolding installed successfully, but it really not.

**Comment by patrickgilmour** [comment] 2019-10-24 00:06
- Laravel Framework 6.4.0
- "laravel/telescope": "^2.1"
- PHP 7.3.7
- DB_CONNECTION=sqlite

Same issue exactly as original poster.

**Comment by authanram** [comment] 2019-11-03 15:19
ty @pszucs 👍 

`TELESCOPE_ENABLED=true` worked for me.

**Comment by HPWebdeveloper** [comment] 2019-11-05 13:38
I had the same problem, 

Laravel Framework 6.4.1

![Screen Shot 2019-11-05 at 10 18 16 AM](https://user-images.githubusercontent.com/16323354/68211162-cae9e380-ffb5-11e9-80fd-4bcd449dd2d7.png)

![Group](https://user-images.githubusercontent.com/16323354/68211261-01bff980-ffb6-11e9-8b7c-e3e42e1d7ef0.png)

So I did:

php artisan cache:clear
and
php artisan config:clear

 I started again from "composer require ..." and I understood I **couldn't** run again:

composer require laravel/telescope

Just because of another new error:

> In ProviderRepository.php line 208:
> 
>   Class 'App\Providers\TelescopeServiceProvider' not found

I found the only change after the last installation command (I mean this):

php artisan telescope:install

was this new line in config/app.php file:

App\Providers\TelescopeServiceProvider::class,

That causes the error and it seems the installation was not complete and only that line was added!

So I **commented** that line in config/app.php file and again only ran :

php artisan telescope:install

It was successful!

I also was surprised that this line: 

App\Providers\TelescopeServiceProvider::class,

was not added again after the second try of installation command.

So I manually uncommented that line in config/app.php

Now everything is fine and works well!

**Comment by alecjamesgarcia** [comment] 2019-11-08 20:46
I was was having the same issue on Laravel Framework 6.5 and PHP 7.2.24. I ended up following some steps that @HPWebdeveloper had done and was able to run the commands. 

1. php artisan cache:clear
2. php artisan config:clear
3. composer require laravel/telescope
4. php artisan telescope:install

At this point I noticed the App\Providers\TelescopeServiceProvider.php file was now there as well as App\config\telescope.php however I do not see a migrate file anywhere. But when continuing on.

5. php artisan migrate

This actually runs the migration. But I have no idea where it is coming from...

**Comment by noeljoseak** [comment] 2019-11-19 07:18
Thanks @alecjamesgarcia. This worked for me. Regarding the migration, it comes from the newly added telescope module in the laravel package within vendor.

**Comment by taylorotwell** [comment] 2019-12-06 20:02
I am able to install Telescope correctly on a fresh Laravel 6 application.

**Closed by taylorotwell** 2019-12-06 20:02 UTC

**Comment by ekstremedia** [comment] 2020-02-24 03:35
I have problems here too, and I think it is related to if you changed "public" folder to the root folder.

**Comment by kyobul** [comment] 2020-04-13 12:13
This problem is still persisting and I don't know why, it is ignored. It exists. Installation is failing.

**Comment by TenZdenda** [comment] 2020-04-24 19:55
I have the same problem on Laravel 7. Please fix it 😞 
file_get_contents(path.../app/Providers/TelescopeServiceProvider.php): failed to open stream: No such file or directory

` at vendor/laravel/telescope/src/Console/InstallCommand.php:77
    73| 
    74|         file_put_contents(app_path('Providers/TelescopeServiceProvider.php'), str_replace(
    75|             "namespace App\Providers;",
    76|             "namespace {$namespace}\Providers;",
  > 77|             file_get_contents(app_path('Providers/TelescopeServiceProvider.php'))
    78|         ));
    79|     }
    80| }
    81| 
`

**Comment by laxsmi** [comment] 2020-04-27 19:32
I encountered a similar issue, I emptied the bootstrap/cache directory and I re-ran all installation steps. It solved my problem.

**Comment by keshansandeepa** [comment] 2020-05-31 20:43
I fixed this issue like this 
1 . Running these commands `php artisan cache:clear and php artisan config:clear`
2.Then Later Require Telescope `composer require laravel/telescope`
3.Then Later I run this command `php artisan telescope:install`
### So Basically It WORKED 

### if you want to remove the package you installed 

Run remove command `composer remove laravel/telescope `
then comment or remove the App\Providers\TelescopeServiceProvider::class, In app/Config Folder

**Comment by ramagkrishna91gmail** [comment] 2020-06-24 09:17
Thanks for the support. It worked after running  php artisan cache:clear &  php artisan config:clear commands.

**Comment by MitchellMcKenna** [comment] 2020-06-24 09:42
Ran into this issue as well. Clearing caches, then removing line `App\Providers\TelescopeServiceProvider::class,` from app/config/app.php as others recommended worked because the [install command won't run if that line already exists](https://github.com/laravel/telescope/blob/5797621d755e1f3019691bd6ec79fdd65bdea46d/src/Console/InstallCommand.php#L56) in the file.

**The Cause:**
For myself the cause was I still had the following in my composer.json:
```
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
```
This was removed from composer.json in 2017:
https://github.com/laravel/laravel/commit/2f4d72699cdc9b7db953055287697a60b6d8b294

**Comment by ivanlara** [comment] 2020-09-22 23:22
I had exactly the same issue, the thing was **I kept opening my .env file from my code editor recent files and it wasn't the one for my current projec**t, so no matter how much I set `TELESCOPE_ENABLED=true` I kept getting all the same errors previously described until I found out. watch out!

**Comment by 0hsn** [comment] 2021-07-11 12:22
PHP 8.x
Laravel 8.x

Had same issue, but [this way](https://github.com/laravel/telescope/issues/732#issuecomment-551983923) fixed it.

**Comment by AtiqurCode** [comment] 2022-05-30 06:01
> php artisan telescope:install

Thanks a lot it working for me
