### ISSUE TITLE
[Feature request] telescope:prune To be Accepting the Raw  String

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/telescope#657] opened 2019-06-27 12:00 UTC
Hi ,

Actually i was using the **Laravel Telescope** in the Production Environment for Logging

So I decided to add the Prune Command To add in the Scheduler 

https://github.com/laravel/telescope/blob/2.0/src/Console/PruneCommand.php#L15

By Default its accepting the hour. So if i need to prune the Data of Last Week 

```
$schedule->command('telescope:prune --hours=720')
                    ->daily();
```

So it will be Useful if the option is changed to 

Current

`protected $signature = 'telescope:prune {--hours=24 : The number of hours to retain Telescope data}';`

Requested

`protected $signature = 'telescope:prune {--timeRange=24 Hours : The time range to retain Telescope data}';`

Current

```
/**
     * Execute the console command.
     *
     * @param  \Laravel\Telescope\Contracts\PrunableRepository  $repository
     * @return void
     */
    public function handle(PrunableRepository $repository)
    {
        $this->info($repository->prune(now()->subHours($this->option('hours'))).' entries pruned.');
    }
```

Requested

```
/**
     * Execute the console command.
     *
     * @param  \Laravel\Telescope\Contracts\PrunableRepository  $repository
     * @return void
     */
    public function handle(PrunableRepository $repository)
    {
        $this->info($repository->prune(now()->sub($this->option('timeRange'))).' entries pruned.');
    }
```

ping @themsaid and @driesvints

**Comment by taylorotwell** [comment] 2019-12-06 20:18
This is not a bug report so I am closing for now.

**Closed by taylorotwell** 2019-12-06 20:18 UTC
