### ISSUE TITLE
Improve memory utilization

### ISSUE THREAD

**Issue by ragingdave** [laravel/telescope#443] opened 2018-11-27 20:20 UTC
It seems that when telescope is logging things that memory usage is straight up out of control.
I have a process that used to complete at my normal configuration of 512MB for the php process, and now requires over 1G to complete and it seems to be failing in memory usage.

Based on the progress bar with memory usage:
Without Telescope enabled: ~34MB
With Telescope enabled: ~414MB(run with php -dmemory_limit=1G artisan ) but dies after the command at 1G

The only unique thing about this command is that dispatches queue jobs from the command and with telescope enabled, it also takes quite some time for the command to actually complete as it just hangs after it is done. Additionally, I have this command configured as an ignored command yet it still seemingly is getting processed.

Sorry for the edit churn, I thought I had the wrong results.

**Comment by themsaid** [comment] 2018-11-28 12:59
> I have a process that used to complete at my normal configuration of 512MB

What do you mean by a process? A console command? A worker? What type of process?

**Comment by themsaid** [comment] 2018-11-30 12:29
@ragingdave I've seen Telescope running in a heavy queue environment without issues, so it seems like something special with your app/queue. Maybe disable the queue watcher in production and try what works until you figure out what's causing the memory leak.

Closing since it's not a general case. Please ping me if you ever identify the root cause of the problem in your app to see if we can change Telescope to handle such edge case.

**Closed by themsaid** 2018-11-30 12:29 UTC
Labels: needs more info

**Comment by bilfeldt** [comment] 2018-12-05 14:10
We are also seeing a huge increase in memory when running PHPUnit tests. The only change between these two tests are `TELESCOPE_ENABLED=true` on the first and `TELESCOPE_ENABLED=false` on the second. Results:
```
Time: 26.56 seconds, Memory: 58.25MB
Time: 13.45 minutes, Memory: 838.25MB
```
![screenshot 2018-12-05 15 08 34](https://user-images.githubusercontent.com/30228807/49518801-d01f4980-f89f-11e8-991a-093879c58894.png)
We are still trying to figure out what is causing this significant memory increase.

**Comment by themsaid** [comment] 2018-12-05 14:35
The application doesn’t terminate between tests, Telescope will keep recording in memory but never stores

**Comment by bilfeldt** [comment] 2018-12-05 15:09
@themsaid great info. So this means that `Telecope` should always be disabled during PHPUnit tests or force terminated between tests somehow to avoid a huge memory buildup caused by the in-memory database tables used by Telescope during PHPUnit tests?

**Comment by dasraab** [comment] 2019-01-31 23:11
@ragingdave i´ve encountered the same problem with a very similar command (dispatches jobs, heavy writing in db). after some testing i found out that the problem is gone if i disable ModelWatcher and QueryWatcher in /config/telescope.php

It seems like telescope does some heavy work after the job is done. like your job, it takes quite some time to end and get back to the console although the work of the command is already done.

**Comment by VictorProductFlow** [comment] 2025-07-07 11:28
Regression on 5.4

Telescope still consumes a lot of memory unless I disable QueryWatcher.
