### ISSUE TITLE
long running job hangs if telescope is enabled

### ISSUE THREAD

**Issue by vesper8** [laravel/telescope#221] opened 2018-10-28 14:26 UTC
ok this one may be hard to reproduce but it's causing me a lot of pain so I thought I would share

First of all, I'm on the latest dev-master 

```
Installing laravel/telescope (dev-master cb05ac7)
```

I have a job that takes about 90 seconds to complete. I'm running it on my dev, on OSX Mojave, and using the sync driver (though I've tried with the redis driver via Horizon and the same thing occurs

If I execute my job, it runs fine, it gets to the end (I have a lot of debugging output throughout so I know it gets to the end and does everything it's supposed to do, but at the end it just hangs, it doesn't exit or finish.

No errors are added to the log, and if I look at the telescope entries table, it only adds about 150 entries. It's a job that consists of a lot of queries and a lot of bulk inserts/updates

now I've made this change to my telescope.php configuration file so I can easily disable the whole thing

```
    'watchers' => env('TELESCOPE', false) ? [
        Watchers\CacheWatcher::class => env('TELESCOPE_CACHE_WATCHER', true),
        Watchers\CommandWatcher::class => env('TELESCOPE_COMMAND_WATCHER', true),
        Watchers\DumpWatcher::class => env('TELESCOPE_DUMP_WATCHER', true),
        Watchers\EventWatcher::class => env('TELESCOPE_EVENT_WATCHER', true),
        Watchers\ExceptionWatcher::class => env('TELESCOPE_EXCEPTION_WATCHER', true),
        Watchers\JobWatcher::class => env('TELESCOPE_JOB_WATCHER', true),
        Watchers\LogWatcher::class => env('TELESCOPE_LOG_WATCHER', true),
        Watchers\MailWatcher::class => env('TELESCOPE_MAIL_WATCHER', true),
        Watchers\ModelWatcher::class => env('TELESCOPE_MODEL_WATCHER', true),
        Watchers\NotificationWatcher::class => env('TELESCOPE_NOTIFICATION_WATCHER', true),

        Watchers\QueryWatcher::class => [
            'enabled' => env('TELESCOPE_QUERY_WATCHER', true),
            'slow' => 100,
        ],

        Watchers\RedisWatcher::class => env('TELESCOPE_REDIS_WATCHER', true),
        Watchers\RequestWatcher::class => env('TELESCOPE_REQUEST_WATCHER', true),
        Watchers\ScheduleWatcher::class => env('TELESCOPE_SCHEDULE_WATCHER', true),
    ] : [],
```

if I add TELESCOPE=false to my .env file

And run the job again, then it doesn't have any problem exiting at the end of the job

if I change it to TRUE, it has the problem.. tested this about a dozen times.. no errors unfortunately, it just hangs

now an interesting thing.. if I set it to TRUE (equivalent of a vanilla configuration) but I add this at the top of my job

```
config(['telescope.watchers' => []]); // disable telescope
```

Then it doesn't add any entries to the telescope tables, BUT it still hangs

If I can provide more details to help you figure out what's wrong please let me know.

In any case, it would be good (needed in my case) to have a way of disabling telescope completely at run-time.. it seems that in the case of my problem.. disabling just the watchers doesn't make my problem go away.

**Comment by themsaid** [comment] 2018-11-13 13:03
Hey,

Since no body else is experiencing the same issue I believe it might be something with your app. Please try to upgrade to latest Telescope and see if the problem disappears.

Closing this issue then unless there are more specific issues that we can fix in Telescope or the issue is reported by someone else.

**Closed by themsaid** 2018-11-13 13:03 UTC
Labels: needs more info

**Comment by Tarpsvo** [comment] 2021-04-28 15:55
I was experiencing the same issue. I also noticed that with Telescope enabled, the used memory would grow little by little and never get garbage collected during the long job.

I eventually optimised the number of SQL queries inside the job and disabled Telescope for the duration of the job:

```
use Laravel\Telescope\Telescope;

Telescope::stopRecording()

// Lots of work

Telescope::startRecording();
```

Only then did the job actually finish. Otherwise the PHP process died (I think?) without any errors and would get timed out by Horizon eventually.

I'm currently looking for a way to disable Telescope for all jobs run by Horizon.

**Comment by ZacharyDuBois** [comment] 2022-01-04 20:28
I also ran into this issue when running a job that processes ~4500 records and runs about ~3-7 queries per record. Adding `Telescope::stopRecording()` and `Telescope::startRecording()` at the beginning of the job and end of the job's `handle()` method resolved it. Went from failing with a OOM error at 512MB to finishing with a peak of 60MB. It seems Telescope saving everything until the end of the process is the main culprit. 

Might want to consider Telescope opening a alternate DB connection and starting a transaction, sending the entries as they happen, then if it didn't meet criteria to save all of them, roll it back, otherwise commit it. Since it's sending it all to the DB, I'd like to think that would help with the memory a bit but I could be wrong. Just a quick thought.

(Thank you so much @Tarpsvo for your comment, I spent literally a few hours trying to figure out how to optimize and diagnose why a simple job was using so much memory! Saved my butt there!)
