### ISSUE TITLE
Large size requests/responses are no longer purged. 

### ISSUE THREAD

**Issue by hendrikxitres** [laravel/telescope#1547] opened 2024-11-19 13:35 UTC
### Telescope Version

5.2.5

### Laravel Version

11.31

### PHP Version

8.3

### Database Driver & Version

Mariadb 10.11.9

### Description

It seems large sized requests are no longer purged. TELESCOPE_RESPONSE_SIZE_LIMIT is at default 128 and my requests are never purged. 

I've tried in new project as well. 

### Steps To Reproduce

1. new project
2. add telescope
3. create route that accepts an base64. 
4. post large base64 encoded file
5. see that telescope fully logged the request.

**Comment by crynobone** [comment] 2024-11-19 13:42
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by hendrikxitres** [comment] 2024-11-20 08:00
Will try to create repository tonight, for now some more info from @LWlook: `In the RequestWatcher class, on line 201, the response data is converted directly to an array without first applying the contentWithinLimits method. This results in the full response data being logged in Telescope, even when a smaller size_limit configuration is set.`

**Comment by crynobone** [comment] 2024-12-02 05:05
> large sized requests are no longer purged

I looked into the history of `RequestWatcher` and don't see any relevant changes since 2021 that indicate a bug was introduced and large requests are no longer pruned for view-based response. It seems that this behavior has been persistent for quite some time. 


Feel free to PR a suggestion to include view based response but at the moment we are marking this as a regression bug.

**Closed as completed by crynobone** 2024-12-02 05:05 UTC
Labels: needs more info
