### ISSUE TITLE
Events not tracked when fired via tinker

### ISSUE THREAD

**Issue by mrmonat** [laravel/telescope#189] opened 2018-10-26 12:45 UTC
I have some custom events, and if I trigger them via Laravel Tinker, the events don't show up in telescope.

**Comment by themsaid** [comment] 2018-10-26 13:28
Please share steps to replicate, I can't replicate it.

**Comment by mrmonat** [comment] 2018-10-26 13:44
All I did was 

`php artisan make:event TestEvent`

`php artisan tinker`

`event(new App\Events\TestEvent())`

but then no new event appeared in Telescope

**Comment by minhajul** [comment] 2018-10-29 19:36
In my cases:

`  $user = \App\User::find(1);
    event(new \App\Events\TestEvent($user));`

This event firing is not tracking by telescope. But when I am returning something after firing an event
like this

`  $user = \App\User::find(1);
    event(new \App\Events\TestEvent($user));
    return view('welcome');`

is perfectly working.

**Comment by Donovan-H** [comment] 2018-11-01 17:07
@themsaid where you able to replicate with those steps?

**Comment by paras-malhotra** [comment] 2018-11-05 21:42
I can confirm that no entries are logged on Tinker (except a command type entry). Not sure why this happens as all other commands seem to work. Something to do with the Psy Shell maybe? @themsaid @deleugpn thoughts?

**Comment by themsaid** [comment] 2018-11-05 21:46
It’s because the app never terminates, Telescope stores the entries when the app terminates or a worker loop is over. So it won’t work with Tinker.

**Comment by paras-malhotra** [comment] 2018-11-05 22:13
Makes sense, I think we can then make a note in the docs and close this issue.

**Comment by trideout** [comment] 2018-11-05 22:14
If you `return false` in tinker before exiting it should exit correctly.

**Comment by themsaid** [comment] 2018-11-13 12:57
Check https://github.com/laravel/telescope/issues/189#issuecomment-436055512

**Closed by themsaid** 2018-11-13 12:57 UTC
Labels: needs more info

**Comment by Dartanjan** [comment] 2020-05-29 10:56
Not sure if this helps anyone, but after I did
```
app()->terminate()
```
in Tinker, I was able to see the SQL log in Telescope that I wasn't seeing with `return false` or such.
