### ISSUE TITLE
Can not capture MongoDB queries

### ISSUE THREAD

**Issue by AmirRezaM75** [laravel/telescope#1542] opened 2024-11-05 12:07 UTC
### Telescope Version

5.2.4

### Laravel Version

10.48.22

### PHP Version

8.2.25

### Database Driver & Version

MongoDB

### Description

After upgrading mongodb/laravel-mongodb package from 3.9 to **5.1.0**, I can no longer see executed queries.
before that it was fine.

### Steps To Reproduce

---

**Comment by crynobone** [comment] 2024-11-06 07:20
Duplicate of mongodb/laravel-mongodb#3183

Telescope wouldn't be able to retrieve executed queries if the event wasn't fired.

**Closed as completed by crynobone** 2024-11-06 07:20 UTC
