### ISSUE TITLE
[Feature request] Collapse dumps

### ISSUE THREAD

**Issue by AndreasHerss** [laravel/telescope#636] opened 2019-05-22 12:28 UTC
It would be nice to be able to collapse the dumps made, as i often dump collections, but as it is right now, i cant collapse data, it's all open.

I would like for it to be like when using dd() and chrome's renderings where i can collapse all childs.

This makes it much easier to inspect data, when not all relations are expanded :)

**Comment by taylorotwell** [comment] 2019-12-06 20:22
This is not a bug report so I am closing for now.

**Closed by taylorotwell** 2019-12-06 20:22 UTC
