### ISSUE TITLE
Telescope on vapor issue

### ISSUE THREAD

**Issue by denjaland** [laravel/telescope#1081] opened 2021-06-23 16:25 UTC
- Telescope Version: 4.5.1
- Laravel Version: 8.48.0
- PHP Version: vapor php-8.0:al2
- Database Driver & Version:

### Description:
To support multi tenancy, whenever we dispatch a queued job, we are adding some payload information on it.
One of these details is a reference to the tenant that the user was working on when the jobs gets dispatched:

```php
$this->app['queue']->createPayloadUsing(function(string $connection, string $queue = null, array $payload = []) {
  return array_merge($payload, ['tenant' => optional(Tenancy::tenant())->id()]);
});
```

Whenever a job is being picked up from the queue, we have the following running:
```php
$this->app['events']->listen(JobProcessing::class, function($event) {
  $tenantId = Arr::get($event->job->payload(), 'tenant');
  if($tenantId) {
    Tenancy::setTenant(Tenant::find($tenantId));
  }
});
```

This basically allows us - when a user does a password reset for instance on any of the tenants - we know what website he was visiting, and can nicely theme our outgoing emails to match the website he was visiting.

This works great, and we have already debugged that Tenant::find($tenantId) does in fact give me the correct tenant.
The functioanlity also works perfectly as long as we don't have the Telescope ModelWatcher activated.

As soon as we do, however, I'm getting an error returned by Telescope:
`Cannot access offset of type string on string`

It is thrown by `/var/task/vendor/laravel/telescope/src/Watchers/ModelWatcher.php` on line 87:

```php
public function recordHydrations($data)
    {
        if (! ($this->options['hydrations'] ?? false)
            || ! $this->shouldRecordHydration($modelClass = get_class($data[0]))) {
            return;
        }

        if (! isset($this->hydrationEntries[$modelClass])) {
            $this->hydrationEntries[$modelClass] = IncomingEntry::make([
                'action' => 'retrieved',
                'model' => $modelClass,
                'count' => 1,
            ])->tags([$modelClass]);

            Telescope::recordModelEvent($this->hydrationEntries[$modelClass]);
        } else {
            $this->hydrationEntries[$modelClass]->content['count']++;  // THIS LINE THROWS THE EXCEPTION
        }
    }
```

At this time I only seem to be able to reproduce this when deployed on vapor, but I'm suspecting it might be a more generic issue with php 8+, but not really sure.

Looking at the code, I don't really know why this error can occur either, but maybe someone here has an idea what might be causing this odd behaviour?

**Comment by driesvints** [comment] 2021-06-24 08:17
Hi @denjaland. Since there's no actionable way for us to reproduce this I'm going to have to close this one. Please try a support channel and when you find a way to reproduce this feel free to open a new ticket. Thanks

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by driesvints** [comment] 2022-01-27 15:46
No plans to reopen. Feel free to send in a PR if you come up with a solution.

**Comment by k0pernikus** [comment] 2022-01-27 15:49
We ran into this as well running telescope on vapor.

@driesvints Why are you closing every issues even if it is not solved? Even if you can't reproduce it, let it be open as a warning to other people looking for the same issue. It was a pain to find this issue. It feels even more frustrating to read: "can't reproduce, will close".

There is no value in having open bugs hidden away when one looks at a project on the issue page.

Is there anything we can provide so that you can reproduce this?

**Comment by driesvints** [comment] 2022-01-31 12:55
Hi all. I tried to dig into this and think I found a reason why this happens specifically on Vapor. I've written a lengthy explanation on a PR I sent in. I'd appreciate it if anyone could try that out on their app: https://github.com/laravel/telescope/pull/1174

**Closed** 2022-02-01 15:02 UTC
Labels: bug
