### ISSUE TITLE
Notifications on production for exceptions etc?

### ISSUE THREAD

**Issue by barryvdh** [laravel/telescope#711] opened 2019-08-23 12:10 UTC
Because Telescope shows detailed information about errors, it might be useful to make it easy to run notifications based on it. Eg. a 'post-store' hook that is able to generate a link to the exception.

For example:
 - Application crashes in production
 - Preview is sent as notification via Slack/Mail to developers with link to page
 - Developer can mark it as resolved (eg. https://github.com/laravel/telescope/pull/710)

**Comment by ahinkle** [comment] 2019-08-30 16:27
I've thought about something of this nature too. I've thought about working on a PR but I've always heard that Laravel Telescope isn't something to be used in Production -- have we gone away from this? 

Anyways, I've been wanting some some notifications when things go wrong such as:
Sending notification when `Watchers` (or similar concept) are triggered:
- Notify via Slack when _(query)_ takes longer than 3000ms
- Notify via Email when _(api endpoint)_ response time takes longer than 3000ms
- Notify via Teams when _(job)_ takes longer than 5000ms

**Comment by barryvdh** [comment] 2019-08-30 17:00
There is an 'afterRecordingHook', but we don't seem to get the recorded entry in there: https://github.com/laravel/telescope/blob/d9c5c53d3a0c60dcd4ef3777884d0cf368eb3e6f/src/Telescope.php#L268

I think something like this could be done in the TelescopeProvider stub:

```php
Telescope::notify(function (IncomingEntry $entry) 
{
    if ($this->app->isLocal()) {
        return;
    }

    if (
        $entry->isReportableException() ||
        $entry->isFailedRequest() ||
        $entry->isFailedJob()
   ) {
        Notification::route('mail', 'taylor@example.com')
            ->notify(EntryNotification::for($entry));
   }
});
```

Where there is a base notification that renders the entry types, adds links/formatting etc.

**Comment by taylorotwell** [comment] 2019-12-06 20:11
This is not a bug report so I am closing for now.

**Closed by taylorotwell** 2019-12-06 20:11 UTC

**Comment by barryvdh** [comment] 2021-03-29 18:31
For future reference and googlers, you can use the `afterStoring` hook:

```php
Telescope::afterStoring(function (array $entries, $batchId) {
    foreach ($entries as $entry) {
        if ($entry instanceof IncomingExceptionEntry) {
            logger()->channel('slack')->critical(
                $entry->exception,
                [
                    'environment' => app()->environment(),
                    'url' => app()->runningInConsole() ? 'CLI' : request()->method() . ' ' . request()->fullUrl(),
                    'user' => $entry->content['user'] ?? '-',
                    'view in Telescope' => url('telescope/exceptions/' . $entry->uuid),
                ]
            );
        }
    }
});
```

**Comment by bdenizar** [comment] 2022-08-05 11:46
> 

If you don’t want to be spam by your app, you can use cache functionnality to wait an amount of time before send notification again when an exception of the same "family" occurs. (In my case I handle a lot of incoming requests)

```php
Telescope::afterStoring(function (array $entries, string $batchId) {
    /** @var IncomingExceptionEntry|IncomingEntry $entry */
    foreach ($entries as $entry) {
        if (!$entry instanceof IncomingExceptionEntry) {
            continue;
        }

        $key = "telescope:anti-spam:{$entry->familyHash}";

        if (cache($key)) {
            continue;
        }

        // Do not spam again for the next five minutes.
        cache([$key => true], now()->addMinutes(5));

        logger()->channel('slack')->critical(
            $entry->exception,
            [
                'environment' => app()->environment(),
                'url' => app()->runningInConsole() ? 'CLI' : request()->method() . ' ' . request()->fullUrl(),
                'user' => $entry->content['user'] ?? '-',
                'view in Telescope' => url("telescope/exceptions/{$entry->uuid}"),
            ]
        );
    }
});
```

**Comment by sidewaysglance** [comment] 2023-07-09 13:13
@barryvdh can you give a more complete example of where to put that snippet? Have been pulling my hair out trying to add it as `protected $middleware` in Kernel.php, using `BeforeMiddleware`, `AfterMiddleware`, trying to add it to `TelescopeServiceProvider`'s `boot` method ... no joy & bothersome.

Any help appreciated.

**Comment by AmmarALHasanat** [comment] 2024-02-20 14:53
I added this code, but he not sends email in my local however if add TelescopeExceptionNotification to other code location that send email
```
Telescope::afterStoring(function (array $entries, $batchId) {
    foreach ($entries as $entry) {
        if ($entry instanceof IncomingExceptionEntry) {
            // send data to eamils 
            Mail::to('test@email.com')
            ->send(new TelescopeExceptionNotification($entry));
        }
    }
});
```

**Comment by Tamas-hi** [comment] 2025-01-29 09:06
In Laravel 11, the following should work: 

TelescopeServiceProvider.php:

```
public function register(): void
{
   // ... existing content
   Telescope::afterStoring(function (array $entries, $batchId) {
            foreach ($entries as $entry) {
                // do whatever you want with the entry
            }
    });
}
```
