### ISSUE TITLE
Telescope not working in non-local environment with non-default auth guard

### ISSUE THREAD

**Issue by jezzdk** [laravel/telescope#501] opened 2018-12-13 09:13 UTC
I can't get telescope to work in a non-local environment. I believe it's because I'm not using 'web' as the default auth guard.
From my config/auth.php:
`
'defaults' => [
    'guard' => 'api',
    'passwords' => 'users',
],
`

I tried switching the default guard to 'web' and it worked right away. However, I have no idea on how to make Telescope use another guard when defining the 'viewTelescope' gate.

**Comment by paras-malhotra** [comment] 2018-12-13 11:32
Duplicate of https://github.com/laravel/telescope/issues/294

**Closed** 2018-12-13 12:16 UTC
