### ISSUE TITLE
Requests invalid time displayed

### ISSUE THREAD

**Issue by mnabialek** [laravel/telescope#110] opened 2018-10-24 07:47 UTC
In JavaScript console and in database (in `telescope_entries`) created_at field has value `2018-10-24 09:37:32`. I have set timezone to `Europe/Paris in `config/app.php`, my local time is also `2018-10-24 09:37:32` (Europe/Warsaw)

But on main telescope page, requests are displayed as `2h ago` and when I go to this single request, for example http://example.com/telescope/requests/8c1874b6-65d5-4d23-96be-eb63a7517f5a I'm getting displayed:

Time | October 24th 2018, 11:37:32 AM (2h ago)

so it displays modified time (+2 hours from now in future) and it says it was 2 hours ago.

**Comment by barryvdh** [comment] 2018-10-24 07:47
Duplicate of https://github.com/laravel/telescope/issues/55

**Closed** 2018-10-24 07:48 UTC
