### ISSUE TITLE
Large amount of MySQL connections being opened and not closed (sleep)

### ISSUE THREAD

**Issue by booni3** [laravel/telescope#818] opened 2020-01-30 13:21 UTC
- Telescope Version: 2.1.4
- Laravel Version: 6.13.1
- PHP Version: 7.3
- Database Driver & Version: MySQL 8.0.11

### Description:
Telescope is opening a huge amount of connections on every request whether or not a query is being ran. I first realised this was happening when my RDS instance kept throwing exceptions due to no available connections. Running 10 queue jobs without any SQL queries inside will easily open 60+ connections.

### Steps To Reproduce:
- Install fresh copy of Laravel
- Install vapor-core, telescope & laravel/ui with Vue auth scaffolding.
- Add my email to the telescope gate. Leave everything else default.
- Create a new job with a `sleep(10)` as the only operation called.
- Deploy via Vapor with RDS micro instance.
- Dispatch 10 instances of this job.

Example MySQL `SHOW PROCESSLIST`  output
![image](https://user-images.githubusercontent.com/20134485/73453062-216f7f80-4363-11ea-9589-27e70e2d2703.png)

- To add, this behaviour seems to be present no matter what I return from the telescope filter (return false) and even seemed to happen if the service provider was conditionally registered to local only.

**Comment by barryvdh** [comment] 2020-01-30 21:02
Do you have a separate connection for Telescope? If so, each job would actually open 2 connections, right?
With Vapor, dispatching 10 jobs at the same time would lead to 10 different containers that open connections. So 10 jobs with 2 connections are 20 connections, that are kept alive until the Lambda container dies (after half a hour or so). Not sure why you would get 60 though..

**Comment by booni3** [comment] 2020-01-31 09:33
My setup is default to what telescope ships with. How would I check to see if it is on a separate connection?

I just checked again (with this project not being invoked for about 24 hours) and it seems that there mya have been some other connections at play when I first reported.

Starting my 10 jobs actually creates 26 sleep connections. At this point I am not logged in and the job consists of nothing but a `sleep(10)` in the handle. I can see why 10 connections would be open to telescope but why would any others be open if we are not hitting any databases?

Additionally should the telescope connections not be closed?

I have since updated my RDS configuration with a `wait_timeout` of 60 seconds, so all these sleep connections are closed after 60 seconds. However,  it does not really help. When running jobs which take 20 - 30 seconds each you can easily send enough to the queue to use up all the connections of the RDS instance (especially with the power of unlimited concurrent execution provided by serverless!)

Do you want me to provide any further information on this? I would love to be able to use Telescope with vapor.

**Comment by themsaid** [comment] 2020-01-31 09:34
Can you replicate the behaviour on your local machine?

**Comment by booni3** [comment] 2020-01-31 09:36
I have not been able to no. I also use telescope on a traditional server setup and have not seen this issue before. I run a lot of queue workers in most of my apps so think it would have been apparent quite quickly.

**Comment by themsaid** [comment] 2020-01-31 09:40
After handling a job, Vapor closes any open database connections. I haven't been able to replicate what you're describing in this issue. As soon as a job is done, I see the connection gets closed.

**Comment by booni3** [comment] 2020-01-31 09:56
Hmm... very strange as I cant really see anything on the application side that I have modified from the default Larval setup. The RDS setup is also completely default although it does have another application connected to it also. My vapor config is updated slightly:

```yaml
id: 6683
name: vapor-test
separate-vendor: true
    staging:
        memory: 1024
        cli-memory: 512
        runtime: php-7.3
        database: test-db
        build:
            - 'composer install'
            - 'php artisan event:cache'
            - 'npm ci && npm run dev && rm -rf node_modules'
        deploy:
          - 'php artisan migrate --force'
        queue-memory: 512
        queue-timeout: 60
        queue-concurrency: 50
```

The only other thing I can think of is spinning up a fresh RDS instance. Can you think of anything else?

**Comment by booni3** [comment] 2020-01-31 09:57
My RDS is on a private network by the way... if that could be any different from your setup?

**Comment by booni3** [comment] 2020-02-02 09:12
I just span up a fresh RDS instance `vapor database my-test-database --dev` and connected my fresh Laravel application to it and I still get the same issue; 21 sleep connections opened up for running my 10 jobs that do not run any queries. If you wanted to see the setup then you can see the commits I have made to the fresh Laravel install here:

https://github.com/booni3/vapor-test/commits/master

The first commit is just Laravel, no changes from myself. I then add Laravel UI, Vapor config and a default telescope setup. I am not too sure how I can get any more paired back than this.

For telescope install I just did:

- `composer require laravel/telescope`
- `php artisan telescope:install`
- `php artisan migrate`
- add my email to the service provider gate

The filter is setup so that nothing is even logging to telescope just yet. If I return true on the filter method then logging does work but the sleep connections issue remain.

I am happy to test anything else that you can think of?

**Comment by themsaid** [comment] 2020-02-02 11:02
Does it stay open forever? What happens if you decrease the number of warmers?

**Comment by booni3** [comment] 2020-02-02 11:05
They stay open until the `wait_timeout` parameter is hit. On a default RDS instance they set this to 8 hours. I can reduce it down to whatever and force the connections to close but they open up so fast that it does not really help. If we are running a few hundred jobs then the max connections limit is hit very quickly.

**Comment by themsaid** [comment] 2020-02-02 11:24
So they only open if you push jobs to queue? Pushing more jobs opens more connections or it’s just a fixed number?

**Comment by booni3** [comment] 2020-02-02 12:13
I did think it was happening on all requests (sure I have seen them come up with just logging in before) but I just double checked and it does appear to only happen when dispatching a job. More connections open up with each run. 

In my test with the `sleep(10)` job, I am dispatching 10 jobs at a time. If I do this 7 times the connections hit the limit (~65 connections).

**Comment by booni3** [comment] 2020-02-02 12:14
it does appear that some of these close actually. Approx 65 open up after running 7 times but now I am back down to 49 connections.

**Comment by nmrdxt** [comment] 2020-02-22 09:36
Happens to me as well. There is a correlation between the amount of "sleep" connections to dispatched jobs. 

I have attempted different combinations of jobs, with different complexity - all, when dispatched, contributed to the "sleep" count.

My config is pretty much the same as booni3's (apart from name changes). Using latest vapor-core.

**Comment by wwallace** [comment] 2020-03-25 02:31
I don't believe this is related to Telescope. I initially started experiencing this when I enabled Telescope. After removing telescope, I still see the amount of `Sleep` connections increment  for each queued job. I have tested by queueing up 40 events per request, and I see the connections increase by 40 until it reaches my instance max(300). I think it was just more noticeable with Telescope because of the amount of queued jobs. queued jobs within Vapor seem to not be reusing connections. 

- Laravel Vapor 1.4.7
- Laravel Framework 6.18.2
- Laravel Nova 2.12.0

**Comment by booni3** [comment] 2020-03-25 09:40
It seems there may be more going on here then.

In my case, even if Telescope is not the root cause, it does result in sleep connections exceeding what my RDS instance can accept.

If I turn Telescope on and run my app in Vapor Staging environment, we start to get max connections exceeded exception on the RDS Large within 30 mins of running various queue jobs.

Turn Telecope off again and we can run indefinitely (months so far).

**Comment by damiantw** [comment] 2020-03-25 16:09
@themsaid Perhaps [RDS Proxy](https://aws.amazon.com/rds/proxy/) can integrated into Vapor to resolve these issues?

**Comment by driesvints** [comment] 2020-04-14 12:05
Hey everyone as most of you came to the conclusion that this is probably not related to Telescope I'm going to close this. But definitely feel free to continue the discussion here to figure out the root cause of the issue. Thanks.

**Closed by driesvints** 2020-04-14 12:05 UTC
Labels: needs more info

**Comment by garrettgjb** [comment] 2020-06-26 03:50
FYI  @booni3 I experienced the same issue where connections to telescope were never released. I hit the connection limit of a medium instance (around 200 i think) with basically no traffic.

Fix was to reuse the main database connection in telescope.php. 

I saw connections sleeping for 4000+ seconds.

My guess is for some reason with telescope the telescope connection is not closed so by reusing my main connection it takes care of the issue because the main connection gets properly closed.

Here's connections after that change:
<img width="484" alt="Screen Shot 2020-06-25 at 8 44 23 PM" src="https://user-images.githubusercontent.com/549725/85818341-4656fb80-b725-11ea-953e-310986ff545d.png">

**Comment by mattias-persson** [comment] 2020-07-10 09:38
@garrettgjb how did you set it up to reuse the main database connection? We might be experiencing the same issue but have made no changes to the telescope config.

**Comment by garrettgjb** [comment] 2020-07-23 19:41
@mattias-persson actually, the problem is still occurring even when I reused my main connection in telescope. I believe it's not a problem with telescope but more likely not releasing the connection that telescope uses on vapor side after telescope captures some sort of data related to jobs. I.e. maybe when a timeout occurs the connection is never released.

**Comment by mattias-persson** [comment] 2020-07-24 14:04
@garrettgjb Yep, we have the same theory of Vapor not closing connections the way we'd expect.

**Comment by garrettgjb** [comment] 2020-07-25 16:24
Just for the record,  I disabled every setting within telescope (except TELESCOPE_ENABLED) and the problem persist. Once I disable TELESCOPE_ENABLED the problem is gone. I looked into using mongo to avoid crashing mysql but that doesn't seem to be supported.

**Comment by jny986** [comment] 2020-10-27 04:50
I had a similar problem and discovered that the issue was caused by the Vapor warming as it was keep 10 instances (by default) warm and each time it hit the warming endpoint it triggered Telescope.

I was able to solve the problem by changing to preserved capacity which does not hit an endpoint to keep instances ready

Hope that helps

**Comment by mattias-persson** [comment] 2020-10-30 09:02
For us it was the package https://github.com/grimzy/laravel-mysql-spatial that prevented the DB connections from being closed. Removing it solved the issue for us.

**Comment by madsem** [comment] 2021-06-19 16:37
I ran into this issue today. Had up to 145 sleeping vapor connections and it blew apart my db instance pretty much.
(Which had no other live traffic)

We're running Telescope in production in default config (except for access config).

This wasn't an issue, but today I added Laravel's batch job table and used Job Batching in one Job class.
Right after I deployed the DB connections started to go crazy.

After reading this here and a few hours of trying and reading, I disabled Telescope, made a deployment and the DB connections dropped from ~100-145 to 4 DB connections in a matter of a minute.

So this has something to do with Telescope I believe, but only under certain conditions.

**Comment by neilgilmour** [comment] 2021-07-01 07:19
I'm so glad i stumbled on this issue. I had the same thing happen to me - default telescope, latest Vapor packages.

I even spun up the biggest RDS instance available just to increase my max connections while i processed a load of jobs. 

Disabling Telescope solved this for me, which is a real shame as Telescope is invaluable!

**Comment by d8vjork** [comment] 2021-07-07 10:55
Even without Telescope we're suffering the same issue, was using Vapor for 3-4 months and issue came early this week.

We also had a very weird problem of duplicated INSERT queries on some audit logs and 150+ connections opened on RDS.

It'll be really nice to know any tips on how to manage all of this, because we're not even abusing on jobs (and the issue came from the login screen from laravel/ui package)

Solution from now on our side was to kill manually all of those opened (sleeping) vapor connections, probably can be something to schedule on the app side or on Vapor's.

**Comment by mattias-persson** [comment] 2021-07-08 14:41
@d8vjork are you using https://github.com/grimzy/laravel-mysql-spatial? That package was the issue for us, and it's a known issue there: https://github.com/grimzy/laravel-mysql-spatial/issues/144

**Comment by d8vjork** [comment] 2021-07-08 14:43
@mattias-persson No, we're not using that package I don't think we either use spatial on our MySQL

**Comment by mattias-persson** [comment] 2021-07-08 14:45
@d8vjork Any other packages manipulating DB-connections? Or are you doing something like that yourselves? Might be worth checking.

**Comment by chasdevs** [comment] 2021-07-30 02:20
Just want to chime in and say we've seen similar issues on our Vapor production application. When a new user signs up for our app, we launch a large amount of jobs (~100-200), and _sometimes_ we see the pattern described above but not all the time. I just reboot the server when this happens, but that's not sustainable.

**Comment by sanjitkung** [comment] 2021-10-19 15:21
I am experiencing similar issue as well. After installing telescope, I started getting connection timeout errors.

**Comment by fjarrett** [comment] 2021-12-20 23:09
I have the same issue with an app running on Vapor. Database connections increase ~35x when Telescope is enabled.

**Comment by diego-lipinski-de-castro** [comment] 2022-02-02 20:04
Same problem, not using vapor tho, just normal machine server

**Comment by mohamed-aiman** [comment] 2022-03-21 20:13
Faced this issue tonight with AWS RDS PostgresSQL instance.

The server was throwing following error.
```
RDS SQLSTATE[08006] [7] FATAL: remaining connection slots are reserved for non-replication superuser connections site:stackoverflow.com
```

Checked the number of connections 
```sql
SELECT count(*) FROM pg_stat_activity;
```
found out that there were 198 connections. Max limit was reached.

So I checked the details of the connections.
```sql
SELECT * FROM pg_stat_activity;
```
Found out that the query in almost all are the same. Here is the value of the query column in all of the connection.
```
update "telescope_entries" set "should_display_on_index" = $1 where "type" = $2 and "family_hash" = $3
```
So had to manually close all of it
```sql
-- to check which connections we are going to close, also do a count. in my case there were 154 connections with same query
select * from pg_stat_activity where datname='yourdbname' and query like '%update "telescope_entries" set "should_display_on_index"%' and datid > 0;
```
and removed those connections
```sql
select pg_terminate_backend(pid) from pg_stat_activity where datname='yourdbname' and query like '%update "telescope_entries" set "should_display_on_index"%' and  datid > 0;
```

Any permanent fix?

**Comment by taylorotwell** [comment] 2022-03-31 22:02
Been digging into this all afternoon. Not much progress 😞 - but, I have some general ideas of what may be happening it's just a bit of a slow process to try to track it down.

**Comment by taylorotwell** [comment] 2022-03-31 22:55
Potential fix: https://github.com/laravel/telescope/pull/1215
