### ISSUE TITLE
Argument 6 in EntryResults needs to be an array and not null

### ISSUE THREAD

**Issue by cmdobueno** [laravel/telescope#33] opened 2018-10-23 16:21 UTC
```
Argument 6 passed to Laravel\Telescope\EntryResult::__construct() must be of the type array, null given, called in /home/envftp/public_html/envision/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 92
```

I found this nasty little bug when attempting to view the requests page. Again I am in the vue-spa and passport realms.

My fix:
Changed line 90 of DatabaseEntriesRepository.php
```
is_array($entry->content) ? $entry->content : [],
```

**Comment by themsaid** [comment] 2018-10-23 16:37
`$entry->content` cannot be null, the column isn't even nullable in the database.

**Comment by cmdobueno** [comment] 2018-10-23 16:42
But it could be invalid/corrupted. Which then would make the parsing the column return null instead of an array.

**Comment by cmdobueno** [comment] 2018-10-23 16:46
I cleared my database and was able to get another invalid record:

Somehow, I created invalid json data in the column of content. In this happening it will then break the requests tab. I apepars to be specifically for requests, and I have not been able to replicate the issues on any other type.

**Comment by themsaid** [comment] 2018-10-23 16:47
If it's returning null then we need to check why it's returning null because it shouldn't. `null` would break a lot of things.

**Comment by themsaid** [comment] 2018-10-23 16:48
What do you see in the DB for the corrupted record? Can you identify why it's unable to store the value into valid JSON?

**Comment by cmdobueno** [comment] 2018-10-23 16:52
3.38 MB (200 KB loaded) (top of the bad data column)

I am curious as to why this request is so massive, but there is a lot of data being passed around with the api. Is it possible the request is too large to be parsed properly?

**Comment by themsaid** [comment] 2018-10-23 16:55
Are you running Telescope in production? If you're and this is the kind of request size your app has, I think you'll need to stop monitoring all requests and only monitor specific ones that you need, otherwise I think you'll need a more advanced storing engine other than the database driver.

**Comment by cmdobueno** [comment] 2018-10-23 17:10
This is a very specific query and basically the only one of its kind, the rest of the queries/requests are rather small. The difficulties of this specific request are appearent. I will most likely see about breaking this request into 2-3 much smaller and hopefully more specific requests and let you know if that fixes the issue.

**Comment by themsaid** [comment] 2018-10-24 10:28
closing for now since it's an edge case.

**Closed by themsaid** 2018-10-24 10:28 UTC
Labels: question

**Comment by egyptik** [comment] 2018-10-24 17:01
Same issue for me with some requests. Caused by the content being longer than currently fits inside MySQL's TEXT type field, which truncates it causing invalid JSON to be passed to the EntryResult constructor.

Changing the `content` column on the `telescope_entries` table to LONGTEXT fixed it for me.

**Comment by necenzurat** [comment] 2018-10-26 04:56
had the same problem, updated had a condition in a request that would exit with no reponse.

**Comment by malinky** [comment] 2018-10-26 13:28
I've had the same issue as @egyptik and the suggestion to change the content column field type to LONGTEXT fixed things. Thanks.

**Comment by andreshg112** [comment] 2018-11-13 00:14
Same here where trying to check Cache.
Laravel Framework 5.7.13
Telescope 0.1.8

@egyptik's workaround didn't work for me.

http://localhost:82/telescope/telescope-api/cache?tag=&before=&take=50&family_hash=
```json
{
    "message": "Argument 6 passed to Laravel\\Telescope\\EntryResult::__construct() must be of the type array, integer given, called in /var/www/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 91",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/var/www/vendor/laravel/telescope/src/EntryResult.php",
    "line": 78,
    "trace": [
        {
            "file": "/var/www/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php",
            "line": 91,
            "function": "__construct",
            "class": "Laravel\\Telescope\\EntryResult",
            "type": "->"
        },
        {
            "function": "Laravel\\Telescope\\Storage\\{closure}",
            "class": "Laravel\\Telescope\\Storage\\DatabaseEntriesRepository",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Support/Collection.php",
            "line": 1011,
            "function": "array_map"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php",
            "line": 261,
            "function": "map",
            "class": "Illuminate\\Support\\Collection",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php",
            "line": 93,
            "function": "map",
            "class": "Illuminate\\Database\\Eloquent\\Collection",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/telescope/src/Http/Controllers/EntryController.php",
            "line": 31,
            "function": "get",
            "class": "Laravel\\Telescope\\Storage\\DatabaseEntriesRepository",
            "type": "->"
        },
        {
            "function": "index",
            "class": "Laravel\\Telescope\\Http\\Controllers\\EntryController",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 212,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 169,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 679,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/telescope/src/Http/Middleware/Authorize.php",
            "line": 18,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Laravel\\Telescope\\Http\\Middleware\\Authorize",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 75,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 63,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",
            "line": 66,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 681,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 656,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 622,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 611,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 176,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/renatomarinho/laravel-page-speed/src/Middleware/PageSpeed.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "RenatoMarinho\\LaravelPageSpeed\\Middleware\\PageSpeed",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 31,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 31,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 62,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 151,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 116,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}
```

**Comment by stephenmelrose** [comment] 2018-11-16 16:01
A cache row is causing this for us,

```               
               sequence: 13
                   uuid: 8c476c0c-1b8a-47fa-84b2-24819142f9ad
               batch_id: 8c476c0c-5fb3-4032-817b-cbbb1249417b
            family_hash: NULL
should_display_on_index: 1
                   type: cache
                content: 0
             created_at: 2018-11-16 07:57:12
```

**Comment by stephenmelrose** [comment] 2018-11-16 16:33
@themsaid I did some further testing to my above example "broken" row ^

Essentially the cache data being stored in `content` was breaking json_encode(). This was due to us caching a `Collection` that contained a model with a binary data field.

I wonder if some protection is required, where is `json_encode()` fails the entry is not logged, or logged with someone denoting bad/missing data?

**Comment by necenzurat** [comment] 2018-11-17 12:47
@stephenmelrose i have the same problem, 1.000.000 rows, i get like 30-40 with content: 0

**Comment by JackEllis** [comment] 2018-11-20 01:14
@themsaid I also had this issue so I'm not sure if it's an edge case. I don't have any data to add here, unfortunately, just a +1 on the problem.

**Comment by cmdobueno** [comment] 2018-11-20 13:32
I believe this is becoming far less of an edge case. I think one of the major issues, is that a lot of people use laravel as an API. Generally API's have much larger request loads than normal website's. For me, there are times I send a paginated list, that includes ~50-75 records. Each of those records have several very important relations have have to be loaded in order to 'do stuff' on the page. These is what, for me, is causing the issues. This may not have any detriment to the overall telescope system, but for me, I just had to add in a failed row handler to allow things not to explode. I do not mind having a few 'bad' rows in the table... though those are generally speaking very bad. 

Thats my input, but take from what you will. This is still in my mind an edge case.... but if too many more people share this issue, it may need pulled out of edge case.

**Comment by narrative1st** [comment] 2018-11-21 01:05
Just started experiencing this as well...changed to LONGTEXT not sure the effect as of yet, but enjoyed Telescope until it stopped spinning on the Scanning...

**Comment by KuenzelIT** [comment] 2018-11-27 15:57
I also have this problem rather quickly after installing telescope. An error handler would be nice.

**Comment by Brigel** [comment] 2019-02-02 11:55
Hi, sorry, but i get same error when i user laravel function "report($exception)". 
PS: I',m updated telescope to last version.(v1.0.13)
