### ISSUE TITLE
File upload causes an exception

### ISSUE THREAD

**Issue by alfonsobries** [laravel/telescope#382] opened 2018-11-13 19:51 UTC
I'm using Laravel media manager package to handle some files uploads, but once I install telescope I always receive an exception that the temp file doesn't exist, you can see in the trace that telescope is involved, the curious thing is that the file is actually stored seems that this exception occurs after the file was uploaded.

I'm guessing that maybe its cause the file manager removes the temporary file and it no longer exists when telescope check the request but not sure.

The trace:
```
The file "/private/var/tmp/phpSlKyP0" does not exist {"userId":744,"email":"bhelm@xxxxxx.com","exception":"[object] (Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"/private/var/tmp/phpSlKyP0\" does not exist at (...)/vendor/symfony/http-foundation/File/File.php:37)
[stacktrace]
#0 (...)/vendor/symfony/http-foundation/File/UploadedFile.php(77): Symfony\\Component\\HttpFoundation\\File\\File->__construct('/private/var/tm...', true)
#1 (...)/vendor/laravel/framework/src/Illuminate/Http/UploadedFile.php(120): Symfony\\Component\\HttpFoundation\\File\\UploadedFile->__construct('/private/var/tm...', 'camera-photo-15...', 'image/png', 0, false)
#2 (...)/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(332): Illuminate\\Http\\UploadedFile::createFromBase(Object(Symfony\\Component\\HttpFoundation\\File\\UploadedFile))
#3 [internal function]: Illuminate\\Http\\Request->Illuminate\\Http\\Concerns\\{closure}(Object(Symfony\\Component\\HttpFoundation\\File\\UploadedFile))
#4 (...)/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(333): array_map(Object(Closure), Array)
#5 (...)/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(331): Illuminate\\Http\\Request->convertUploadedFiles(Array)
#6 [internal function]: Illuminate\\Http\\Request->Illuminate\\Http\\Concerns\\{closure}(Array)
#7 (...)/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(333): array_map(Object(Closure), Array)
#8 (...)/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(314): Illuminate\\Http\\Request->convertUploadedFiles(Array)
#9 (...)/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(184): Illuminate\\Http\\Request->allFiles()
#10 (...)/vendor/laravel/telescope/src/Watchers/RequestWatcher.php(43): Illuminate\\Http\\Request->all()
#11 (...)/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Laravel\\Telescope\\Watchers\\RequestWatcher->recordRequest(Object(Illuminate\\Foundation\\Http\\Events\\RequestHandled))
#12 (...)/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Foun...', Array)
#13 (...)/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(128): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Foun...')
#14 (...)/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
"} 

```

If its helpful in some way this is the part of the code that handles the file upload, but the exception occurs in the telescope monitor.
```
if (!$file->isValid()) {
    return $this->returnError($request, 'The uploaded file is not valid.');
}

$file_name = $file->getClientOriginalName();
$file_name_extension = pathinfo($file_name, PATHINFO_EXTENSION);
$file_name_name = pathinfo($file_name, PATHINFO_FILENAME);

$name = $this->manager->setFilename($request->input('name', $file_name_name), 

$media = $record->addMedia($file)
    ->usingName($name)
    ->usingFileName($file_name)
    ->withCustomProperties($custom_properties)
    ->toMediaCollection($this->registered_models[$base_folder]['collection']);  
```

**Comment by alfonsobries** [comment] 2018-11-13 20:12
I explore the trace and I feel more secure that its caused because the file manager removes the temp file, maybe telescope will need to filter the files that doesnt exists or something

**Comment by paras-malhotra** [comment] 2018-11-14 06:02
Duplicate of #377. This has been fixed and will be available in the next release.

**Closed** 2018-11-14 08:38 UTC
