### ISSUE TITLE
[Feature Request] Measuring Tool / Timeline

### ISSUE THREAD

**Issue by christophmayrhofer** [laravel/telescope#674] opened 2019-08-05 09:57 UTC
Is there some way to get a timeline for the requests? I.e. I would like a function like:
start_measure($id), end_measure($id) and then I would get those timings logged in telescope. 
Similar to the way debugbar and clockwork provide timelines. 
(This feature is actually the only reason why I still have to use clockwork alongside Telescope)

**Comment by barryvdh** [comment] 2019-08-15 08:01
We could look at the Symfony Profiler, which has a 'simple' measuring toolbar, which we should be able to implement: https://github.com/symfony/web-profiler-bundle/blob/master/Resources/views/Collector/time.html.twig

- Create a new EntryType for timing entries
- Add a Watcher that can start/stop/add timing entries with a label/type/start/stop
- Render the events in a timeline (like Symfony above, but there are probably other libraries that culd be used).

The watcher could also register some points in the timeline bij listening to the events. Example from Symfony:

![image](https://user-images.githubusercontent.com/973269/63081286-8533f680-bf43-11e9-81bf-ff763896323e.png)

**Comment by barryvdh** [comment] 2019-08-15 20:27
So I've played with it a bit, I though of this approach:
 - Create a 'timing' screen, which consists of the existing entries that have timing data
 - Add default timing data to collectors when they are added (time of adding = time that event ended - roughly
- When possible, determine the start time (eg. based on duration/time of sql etc)
- Render the entries in a table, using CSS with the calculated margin/width to generate a timeline, link to the details.

See work in progress: https://github.com/laravel/telescope/compare/2.0...barryvdh:feat-timing?expand=1

So basically this:
<img width="955" alt="Screen Shot 2019-08-15 at 22 19 56" src="https://user-images.githubusercontent.com/973269/63124416-8731a000-bfab-11e9-9bfa-c6db6b310a8f.png">

What this would further need:
 - A nice layout (eg. show the duration properly and apply nice labels to them, color them by type etc.
 - Add timing info where possible/relevant
 - Create a TimingEntry type to add custom timing events, basically the same as normal entries but with start/end and a label.
 - Add a Watcher/method to add the entries.

So not sure if there is any interest, before I continue with more work on this ;)
Also my CSS/design experience probably isn't enough to make it pretty.

**Comment by christophmayrhofer** [comment] 2019-08-16 14:00
@barryvdh Thanks for the effort. I just wanted to have a look at it, but it seems the way I am adding it to my project does not work:

I have added this to my composer.json:

```"repositories": [
    {
      "type": "package",
      "package": {
        "name": "laravel/telescope",
        "version": "2.0",
        "source": {
          "url": "https://github.com/barryvdh/telescope.git",
          "type": "git",
          "reference": "feat-timing"
        }
      }
    }],```

then I have run ```composer require larave/telescope``` and ```composer dump-autoload```, but the php artisan telescope commands are still not available and the /telescope route returns 404...

**Comment by barryvdh** [comment] 2019-08-16 14:38
You also have to enable it like before and compile it from the vendor dir + publish it.

**Comment by christophmayrhofer** [comment] 2019-08-16 14:53
@barryvdh I have added it to the Providers array and tried to run ```php artisan telescope:install```
but I get ```There are no commands defined in the "telescope" namespace. ```
I have never required a package from github this way, so I am not sure if there are any differences from requiring directly from the composer packagist directory.

**Comment by barryvdh** [comment] 2019-08-16 15:00
Ahr, not 100% sure. I've just created a new Laravel install. Then `composer require laravel/telescope --prefer-source` to install it from git. Then go the the vendor folder, add it as remote (`git add remote barryvdh https://github.com/barryvdh/telescope.git` and then fetch + checkout `feat-timing` from my branch, run `npm install && npm run dev` and then install+publish Telescope like usual.

**Comment by christophmayrhofer** [comment] 2019-08-18 20:59
@barryvdh Thanks, I could make it work with your tips. I have now created a pull request to your fork with your initial draft.

**Comment by taylorotwell** [comment] 2019-12-06 20:13
This is not a bug report so I am closing for now.

**Closed by taylorotwell** 2019-12-06 20:13 UTC
