### ISSUE TITLE
Call to undefined method Illuminate\Support\Testing\Fakes\EventFake::getListeners()

### ISSUE THREAD

**Issue by specialtactics** [laravel/telescope#573] opened 2019-03-04 05:28 UTC
Hi

We've just updated to Laravel 5.8, and using the latest Telescope v2.0.0, and we get this error in some unit tests - seems to be because Telescope is trying to run getListeners() and it doesn't exist.

```
   │ Error: Call to undefined method Illuminate\Support\Testing\Fakes\EventFake::getListeners()
   │ 
   │ /var/www/vendor/laravel/telescope/src/Watchers/EventWatcher.php:82
   │ /var/www/vendor/laravel/telescope/src/Watchers/EventWatcher.php:46
   │ /var/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:344
   │ /var/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:196
   │ /var/www/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/EventFake.php:201
   │ /var/www/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/EventFake.php:257
   │ /var/www/vendor/owen-it/laravel-auditing/src/Auditor.php:99
   │ /var/www/vendor/owen-it/laravel-auditing/src/Auditor.php:65
   │ /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:237
   │ /var/www/vendor/owen-it/laravel-auditing/src/AuditableObserver.php:38
```

**Comment by specialtactics** [comment] 2019-03-04 05:30
I am not sure if the solution is to not record fake events (and hence check the event class in the process), or if Laravel should implement this function in it's fake event class (seems like a better option).

But I also don't know the context of why this suddenly broke in 5.8, so I thought I'd raise it first and get some commentary.

**Comment by themsaid** [comment] 2019-03-05 12:23
Are you using `Telescope::recordFrameworkEvents()`?

Telescope ignores all `Illuminate\*` events by default, which includes the fake event.

**Comment by specialtactics** [comment] 2019-03-05 14:14
Hi @themsaid 

I cannot see "recordFrameworkEvents" anywhere in our tests nor the audit package which is throwing the error. I have not heard of this, so unless it's something which defaults to being on / used by default, I doubt this is the case.

**Comment by themsaid** [comment] 2019-03-06 08:06
Well, I can't replicate the issue so you'll have to test it on a fresh Laravel app and show me some steps to replicate. 

Otherwise `EventFake` won't be logged by default, that's the result I'm getting.

**Comment by willemo** [comment] 2019-05-29 14:41
@themsaid I'm also getting this issue. I've tried to debug the code a bit and this is what happens for us when we have  a test that fakes the event dispatcher:

I added a breakpoint at `EventFake:201` to see which events passed through this line and at first it was a bunch of eloquent events, which went fine, but as soon as an event from a library was passed to that line the exception occurs.

Obviously Telescope ignores all the eloquent events, so this is the first event that occurs that Telescope tries to format the listeners for. Since faking events replaces the default event dispatcher with EventFake and EventFake doesn't have a `getListeners()` method, Telescope's event watcher can't format the listeners for the given event.

I hope this information helps a bit.

**Comment by jorenvh** [comment] 2020-04-06 11:29
I'm seeing the same behavior in one of my applications. On the other hand this also makes me reconsider if Telescope is actually needed when running the tests suite.

For now I have disabled telescope in the testing env. If I have a bit time I will dig in a bit more and try to find a solution for this.

**Comment by driesvints** [comment] 2020-04-06 11:31
@jorenvh Telescope should definitely be disabled when running your tests.

**Comment by jorenvh** [comment] 2020-04-06 11:53
@driesvints Thanks for confirming that!

Just thinking out loud, but wouldn't it be nice if it could be configured this way by default? I haven't looked into it yet so I'm not even sure it's possible. Would you accept a PR that adds this behavior by default?

**Comment by driesvints** [comment] 2020-04-06 12:15
@jorenvh it should already be disabled by default I believe 🤔

**Comment by driesvints** [comment] 2020-04-07 13:03
I just confirmed that Telescope is indeed not disabled by default during testing and nor should it. So we'll investigate this issue.

**Comment by driesvints** [comment] 2020-04-07 13:08
@specialtactics please provide some code to reproduce this.

**Comment by jorenvh** [comment] 2020-04-07 14:43
@driesvints below a simplified representation of the failing code on my end.

**Requirement:** Telescope should be enabled when running the test suite

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SomeModel extends Model
{
    // ...
    
    protected $dispatchesEvents = [
        'saving' => SavingSomeModelEvent::class,
    ];

    // ...
}
```

```
<?php

namespace App\Events;

use App\Models\SomeModel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class SavingSomeModelEvent
{
    use Dispatchable, SerializesModels;

    /**
     * @var \App\Models\SomeModel
     */
    public $someModel;

    public function __construct(SomeModel $someModel)
    {
        $this->someModel = $someModel;
    }
}

```

```
<?php

namespace Tests\Feature;

use Tests\TestCase;

class SomeTest extends TestCase
{
    protected $someModel;
    
    protected function setUp(): void
    {
        parent::setUp();
        
        Event::fake(SavingSomeModelEvent::class);

        $this->someModel = factory(SomeModel::class)->create();
    }

```

Running the test suite results in the below (I filtered some data from the below)

```
Error: Call to undefined method Illuminate\Support\Testing\Fakes\EventFake::getListeners()
/vendor/laravel/telescope/src/Watchers/EventWatcher.php:83
/vendor/laravel/telescope/src/Watchers/EventWatcher.php:47
/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:344
/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:196
/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/EventFake.php:201
/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/EventFake.php:257
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:205
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:180
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:651
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:206
/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php:176
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:207
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:181
/path/to/my/factory/file.php:linenumber
/tests/Feature/SomeTest.php:linenumber
```

Hope this helps in resolving the issue, if you need more input or you can't reproduce it let me know and I will try to spin up a new Laravel install where you can reproduce the issue.

**Comment by driesvints** [comment] 2020-04-09 09:05
Thanks @jorenvh. That helped. I've sent in a fix for this here: https://github.com/laravel/telescope/pull/866

**Comment by jorenvh** [comment] 2020-04-09 12:34
Thanks @driesvints 🙌

**Closed** 2020-04-09 14:25 UTC
Labels: needs more info

**Comment by driesvints** [comment] 2020-04-09 17:17
Just fyi: a PR to disable Telescope by default was just merged on the skeleton: https://github.com/laravel/laravel/pull/5277
